name: Trigger auto deployment for ca-williamhe-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-williamhe-app-AutoDeployTrigger-a1e38bb5-0122-4015-9291-24ab1c203e29.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAWILLIAMHEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAWILLIAMHEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAWILLIAMHEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          mylabel: _targetLabel_
          registryUrl: acatestregistry.azurecr.io
          registryUsername: ${{ secrets.CAWILLIAMHEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAWILLIAMHEAPP_REGISTRY_PASSWORD }}
          containerAppName: ca-williamhe-app
          resourceGroup: capps-williamhe3-rg
          imageToBuild: acatestregistry.azurecr.io/mcr.microsoft.com/k8se/quickstart:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


