name: Trigger auto deployment for test-s2c-managed-env-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-s2c-managed-env-ca-AutoDeployTrigger-ed4c0741-f5ca-41b5-b414-539d3248e38f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTS2CMANAGEDENVCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTS2CMANAGEDENVCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTS2CMANAGEDENVCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.TESTS2CMANAGEDENVCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTS2CMANAGEDENVCA_REGISTRY_PASSWORD }}
          containerAppName: test-s2c-managed-env-ca
          resourceGroup: test-s2c-managed-env
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


